# Generated by Django 4.2.4 on 2023-08-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='none', max_length=30)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
